apiVersion: v1
kind: Service
metadata:
  name: sink-service
  labels:
    app: sink-host-netdevice
    release: firewall-host-netdevice
    chart: sink-host-netdevice
spec:
  type: NodePort
  ports:
    - port: 667
      nodePort: 30667 
  selector:
    app: sink-host-netdevice
    release: firewall-host-netdevice
