apiVersion: v1
kind: Service
metadata:
  name: packetgen-service
  labels:
    app: pktgen-host-netdevice
    chart: pktgen-host-netdevice
    release: firewall-host-netdevice
spec:
  type: NodePort
  ports:
    - port: 2831
      nodePort: 30831
  selector:
    app: pktgen-host-netdevice
    release: firewall-host-netdevice
