apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: host-device-veth12
  namespace: example
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "host-device",
      "device": "veth12"
    }'

---
  
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: host-device-veth11
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "host-device",
      "device": "veth11"
    }'
